### ISSUE TITLE
Downscaling images with assetpack/free-tex-packer-core?

### ISSUE THREAD

**Issue by reececomo** [pixijs/assetpack#66]
We'd like to generate a high DPI `@2x` spritesheet (plus `@1x` and `@0.5x`), but upscaling low resolution assets creates a blurry spritesheet.

What might the happy path be, if we were starting with high resolution assets (`@2x` and `@3x`)? e.g.

```
  /sheet{tps}/
      ball@3x.png    ← 600 x 600
      player@3x.png  ← 600 x 1200
      ...
```

(the desired result is that `ball` would be 400 x 400 in `sheet@2x`)

Possibly relates to #50

**Comment by reececomo** [comment]
Alternatively, it would be phenomenal if [Spritesheet](https://github.com/pixijs/pixijs/blob/cde22b16a1d5a1e9b8800538521fe9488735c242/src/spritesheet/Spritesheet.ts#L369) could detect individual frame texture resolutions (either from name, or if it support a "scale" property on frames).

```
texture.resolution = spritesheet.meta.scale * frame.scale
```

Then we could just pack mixed assets - like Asset Catalog in iOS:

```
sheet{tps}/
    background@2x.png   ← 1920x1080
    ball@3x.png         ← 600x600
    ...
```

And use them however we like:

```ts
// load the desired spritesheet scale for the platform

const background = new Sprite(spritesheet.textures['ball']);
const ball = new Sprite(spritesheet.textures['ball']);

// background.size: 960w 540h
// background.texture.size: 1920w 1080h
// ball.size: 200w 200h
// ball.texture.size: 400w 400h
```

**Comment by reececomo** [comment]
Alternatively, it would be phenomenal if [Spritesheet](https://github.com/pixijs/pixijs/blob/cde22b16a1d5a1e9b8800538521fe9488735c242/src/spritesheet/Spritesheet.ts#L369) could detect individual frame texture resolutions (either from name, or if it support a "scale" property on frames).

```
texture.resolution = spritesheet.meta.scale * frame.scale
```

Then we could just pack mixed assets - like Asset Catalog in iOS:

```
sheet{tps}/
    background@2x.png   ← 1920x1080
    ball@3x.png         ← 600x600
    ...
```

And use them however we like:

```ts
// load the desired spritesheet scale for the platform

const background = new Sprite(spritesheet.textures['ball']);
    // background.size: 960x540
    // background.texture.size: 1920x1080

const ball = new Sprite(spritesheet.textures['ball']);
    // ball.size: 200x200
    // ball.texture.size: 400x400
```

**Comment by Zyie** [comment]
Hey, if you start with 2x assets, you should be able to pass `{ resolutions: { high: 2, default: 1, low: 0.5 } }` to both the mipmap and spritesheet plugin. This will take the 2x assets and produce the additional 1x and 0.5x versions

**Comment by reececomo** [comment]
Thanks!
