### ISSUE TITLE
Assetpack creates wrong aliases

### ISSUE THREAD

**Issue by YVeselovskyi** [pixijs/assetpack#76]
This is my folders structure, it was working on 0.8.0 version, but now, when assets are built it ignores the fact, that they are inside folders and makes an alias with just their file names, like instead of `animations/water` in packed json it is `water`.

<img width="378" alt="Знімок екрана 2024-08-14 о 14 49 11" src="https://github.com/user-attachments/assets/d6aa74c6-4cac-4b08-a10e-a9bb4c4c72d9">

my config:

<img width="919" alt="Знімок екрана 2024-08-14 о 14 53 28" src="https://github.com/user-attachments/assets/4e30481e-3871-4f9f-98d1-cfe83730630c">

`nameStyle: 'relative'` - this is not working at all, no matter where I put it.

how can I fix it?

Thanks!

**Comment by Zyie** [comment]
Hey the config here looks a little off, can you try this

```js
import { pixiPipes } from "@assetpack/core/pixi";

export default {
  entry: './raw-assets',
  output: './public',
  pipes: [
    ...pixiPipes({
        texturePacker: { nameStyle: "relative" },
        manifest: { output: './src/manifest.json' }
    }),
  ],
};
```

**Comment by YVeselovskyi** [comment]
I tried all variants, it still ignores :(

**Comment by Zyie** [comment]
ok yeah i can recreate this

will take a look!

**Comment by Zyie** [comment]
@YVeselovskyi I've got a PR to fix the issue, if you want an immediate solution try turning `removeFileExtension: false`

**Comment by YVeselovskyi** [comment]
@Zyie thanks!
also fonts are not working, I have a fonts folder, they are converting to woff2, but pixi.js does not recognize them at all.

**Comment by Zyie** [comment]
> please , help

Hey @antag0n1st do you by chance have two or more files named `logo_jili`?
The manifest removes any name clashes

**Comment by antag0n1st** [comment]
@Zyie  
yes that was the problem , thank you for pointing that.
Is it possible that assetpack can log a warning for this ?

**Comment by antag0n1st** [comment]
@Zyie actually I need to have them with duplicate names. 
As I want to load language dependent assets in different language bundles.

for example 
en{m}/title.png
de{m}/title.png

and It will be a different title based on the language.

**Comment by YVeselovskyi** [comment]
@Zyie hello!
when you will be able to merge that PR with fix?

**Comment by sarahgaucimizzi** [comment]
@Zyie Using latest 1.1.1 with this config:

```
import { pixiPipes } from '@assetpack/core/pixi'

export default {
  entry: './raw-assets',
  output: './public/assets/',
  pipes: [
    ...pixiPipes({
      cacheBust: true,
      texturePacker: {
        texturePacker: {
          nameStyle: 'relative'
        }
      }
    })
  ]
}
```

I still get this warning 
<img width="1300" alt="image" src="https://github.com/user-attachments/assets/2300ed3a-9872-4975-8b4a-4e752cfbb6d8">
and this output
<img width="514" alt="image" src="https://github.com/user-attachments/assets/12bad56f-6ca4-4a6b-9df1-e27a973fa056">

Like the scenario mentioned above with the languages, I want them to have identical names but distinguished by their path/folder name to use landscape and portrait assets in the respective scenario.

Am I missing something else in the config?

**Comment by Zyie** [comment]
Hey @sarahgaucimizzi 

Can you provide me with your folder structure layout so i can see if i can recreate the error?

If you cant provide a screenshot then this tool is very useful: [Tree](https://tree.nathanfriend.io/?s=(%27options!(%27fancy!true~fullPath0~trailingSlash0~rootDot0)~4(%274%272assets3*2game(m)3**2mobile3*52test_banner.png3%27)~version!%271%27)5%200!false2-%203%5Cn4source!5*%20%0154320*)

**Comment by sarahgaucimizzi** [comment]
Hi thanks for the quick response, this is a screenshot of the folder structure with the issue being about test_banner.png (the rest of the assets are fine)

<img width="311" alt="image" src="https://github.com/user-attachments/assets/cbdd8dad-f832-4dbb-88a7-73f96017f927">

Since posting I also tried with texture packer pipe instead of the pixiPipe just incase but still same issue

```
import { audio } from '@assetpack/core/ffmpeg'
import { json } from '@assetpack/core/json'
import { pixiManifest } from '@assetpack/core/manifest'
import { texturePacker } from '@assetpack/core/texture-packer'
import { webfont } from '@assetpack/core/webfont'
// import { pixiTexturePacker } from '@assetpack/plugin-texture-packer'

export default {
  entry: './raw-assets',
  output: './public/assets/',
  // cache: false,
  pipes: [
    json(),
    webfont(),
    audio(),
    texturePacker({
      texturePacker: {
        nameStyle: 'relative',
        removeFileExtension: true
      }
    }),
    pixiManifest({
      output: './public/assets/assets-manifest.json'
    })
    // ...pixiPipes({
    //   cacheBust: false,
    //   // texturePacker: {
    //   //   texturePacker: {
    //   //     removeFileExtension: true,
    //   //     nameStyle: 'relative'
    //   //   }
    //   // }
    // })
  ]
}

```

**Comment by Zyie** [comment]
ahh ok, I think I need to introduce another naming strategy that includes the folder name that has the `{tps}` tag on it. The `'relative'` strategy only takes the folder structure inside the `{tps}` into account.

```
assets
└── mobile{m}
    ├── landscape{tps}
    │   └── landscape
    │       └── test_banner.png
    └── portrait{tps}
        └── portrait  
            └── test_banner.png
```
so in this example the names would be `portrait/test_banner.png` and `landscape/test_banner.png`

**Comment by sarahgaucimizzi** [comment]
I see, sorry did not understand this from the docs, to resolve the warning I had to separate again mobile and desktop since they both have landscape.

<img width="420" alt="image" src="https://github.com/user-attachments/assets/4e130b21-834b-4dec-b3ff-99160232be1d">

and the output is what I expect thanks 🙏 

<img width="453" alt="image" src="https://github.com/user-attachments/assets/178b33f5-2a1a-42df-a0f5-d46e3c374843">
