### ISSUE TITLE
Incorrect manifest bundle names in v1

### ISSUE THREAD

**Issue by CatchABus** [pixijs/assetpack#87]
After 0.8.0, manifest plugin generates manifest file with incorrect bundle names.
Say I have a `joey{m}/splash{m}` path that contains images. I'd expect its bundle name to be `joey/splash` in manifest.

This worked with old manifest plugin:
```json
{
  "bundles": [
    {
      "name": "joey",
      "assets": []
    },
    {
      "name": "joey/splash",
      "assets": [
        ...
      ]
  ]
}
```

However, assetpack 1.x.x ignores the parent folder:
```json
{
  "bundles": [
    {
      "name": "joey",
      "assets": []
    },
    {
      "name": "splash",
      "assets": [
        ...
      ]
  ]
}
```

This will go horribly wrong if I have another splash folder that is in the same level as `joey` folder.

v0.8.0 used this function to transform file path into a bundle name: https://github.com/pixijs/assetpack/blob/38e872a82f45ce46edeefa5b13ee6d5973d8daa6/packages/manifest/src/utils.ts#L1
And it was used here: https://github.com/pixijs/assetpack/blob/38e872a82f45ce46edeefa5b13ee6d5973d8daa6/packages/manifest/src/pixi.ts#L102

**Comment by CatchABus** [comment]
I could create a PR to re-implement this using a more performant way like the existing asset tree parents to generate the name.
The question is, would we want this configurable from now on?

**Comment by Zyie** [comment]
Hey @CatchABus if you want to create a PR for this that would be great!

I was thinking this would be a configurable option called `namingStrategy` like how the spritesheet plugin, something like `namingStrategy: 'short' | 'full'`

we keep `short` as the default to avoid the breaking change
we should also warn when two `short` manifest names are the same and fallback to there`full` named version
