### ISSUE TITLE
Bug: font family incorrectly including tags in name

### ISSUE THREAD

**Issue by YVeselovskyi** [pixijs/assetpack#97]
I cannot build and use my assets after upgrading from 0.8.0 to 1.2.0.

This is my folder structure:

![Image](https://github.com/user-attachments/assets/96957d0b-f669-4670-9256-25255c8098fe)

This was my config on 0.8.0 and all was working great

```
import { compressJpg, compressPng } from '@assetpack/plugin-compress';
import { pixiTexturePacker } from '@assetpack/plugin-texture-packer';
import { pixiManifest } from '@assetpack/plugin-manifest';
import { webfont } from '@assetpack/plugin-webfont';
import { audio } from '@assetpack/plugin-ffmpeg';
import { json } from '@assetpack/plugin-json';

export default {
  entry: './raw-assets',
  output: './public',
  cache: false,
  plugins: {
    webfont: webfont(),
    compressJpg: compressJpg(),
    compressPng: compressPng(),
    audio: audio(),
    json: json(),
    texture: pixiTexturePacker({
      texturePacker: {
        removeFileExtension: true,
      },
    }),
    manifest: pixiManifest({
      output: './src/manifest.json',
    }),
  },
};
```

This is my config on 1.2.0

```
import { pixiPipes } from '@assetpack/core/pixi';

export default {
  entry: './raw-assets',
  output: './public',
  pipes: [
    ...pixiPipes({
      resolutions: { high: 3, default: 2, low: 1 },
      manifest: {
        trimExtensions: true
      },
      texturePacker: { texturePacker: { nameStyle: 'relative', removeFileExtension: true }},
    }),
  ],
};

```

and I always keep getting this error:

``` Error: [Loader.load] Failed to load http://localhost:5173/images/preload/preload@1x.json```

so it's doesn't take hash into consideration

could you help me, please?

**Comment by YVeselovskyi** [comment]
hello, @Zyie!

actually I took config from bubbo bubbo:

import { pixiPipes } from '@assetpack/core/pixi';

```
export default {
  entry: './raw-assets',
  output: './public/assets/',
  cache: true,
  pipes: [
    ...pixiPipes({
      cacheBust: false,
      texturePacker: {
        texturePacker: {
          removeFileExtension: true,
        },
      },
      manifest: {
        output: './src/manifest.json',
      },
    }),
  ],
};
```

but I still see this issue :(

this is my `assets.js` file:

```

import {
  Assets,
  extensions,
  ExtensionType,
  Resolver,
  resolveTextureUrl,
} from 'pixi.js';
import manifest from './manifest.json';

export const resolveJsonUrl = {
  extension: ExtensionType.ResolveParser,
  test: (value) => Resolver.RETINA_PREFIX.test(value) && value.endsWith('.json'),
  parse: resolveTextureUrl.parse,
};

extensions.add(resolveJsonUrl);

/** Initialise and start background loading of all assets */
export async function initAssets(onProgress = () => {}) {
  await Assets.init({ manifest, basePath: 'assets/' });

  // Load the preload and default bundles first (default means fonts etc.)

  await Assets.loadBundle(['images/preload', 'default'], onProgress);

  const skipBundle = ['images/tutorial'];
  const allBundles = manifest.bundles.map((item) => item.name).filter((item) => !skipBundle.includes(item));

  Assets.backgroundLoadBundle(allBundles);
}

export function isBundleLoaded(bundle) {
  const bundleManifest = manifest.bundles.find((b) => b.name === bundle);

  if (!bundleManifest) return false;

  // eslint-disable-next-line no-restricted-syntax
  for (const asset of bundleManifest.assets) {
    if (!Assets.cache.has(asset.alias)) return false;
  }

  return true;
}

export function areBundlesLoaded(bundles) {
  // eslint-disable-next-line no-restricted-syntax
  for (const name of bundles) {
    if (!isBundleLoaded(name)) return false;
  }
  return true;
}
```

**Comment by Zyie** [comment]
I don't see anything obviously wrong here

Are you able to provide the `manifest.json`?

**Comment by Zyie** [comment]
ahh ok i think i see the issue

you are doing `Assets.loadBundle(['images/preload', 'default'])` but if you looks at the bundle names it should be `Assets.loadBundle(['preload', 'default'])`

same for `skipBundle` this should just be `tutorial`

**Comment by YVeselovskyi** [comment]
It didn't help, but I see, that I don't have json file in `.assetpack` folder, just the audio folder, where another audio folder is nested 🤕

**Comment by YVeselovskyi** [comment]
loading screen is working now!

`static assetBundles = ['preload'];` - I removed `images/` from here :)

but now it can't find assets, which are nested in game-screen folder, can I fix it somehow?

![Image](https://github.com/user-attachments/assets/a08ff27c-56c4-4d82-b1f5-b427803f0877)

**Comment by YVeselovskyi** [comment]
```
import { pixiPipes } from '@assetpack/core/pixi';

export default {
  entry: './raw-assets',
  output: './public/assets/',
  cache: true,
  pipes: [
    ...pixiPipes({
      cacheBust: false,
      texturePacker: {
        texturePacker: {
          nameStyle: 'relative',
          removeFileExtension: true,
        },
      },
      manifest: {
        output: './src/manifest.json',
      },
    }),
  ],
};
```

I added `nameStyle: 'relative'` and finally built assets :)

the only issue now is that fonts are not displaying, but they are built properly

**Comment by YVeselovskyi** [comment]
@Zyie do you have any idea why fonts can be not loaded?
I made all the same, as in bubbo-bubbo example

**Comment by Zyie** [comment]
@YVeselovskyi can you show me a screenshot of the fonts folder?

**Comment by YVeselovskyi** [comment]
raw:

![Image](https://github.com/user-attachments/assets/29bba6a7-8e18-40cf-a4fa-861cbfe54352)

built:

![Image](https://github.com/user-attachments/assets/f4a01721-8491-42f5-b122-0c1af1785869)

how I use it:

```
RUBIK_PASTEL_YELLOW: {
  fontFamily: 'Rubik Regular',
  fontWeight: 400,
  fill: COLORS.PASTEL_YELLOW,
},
```

**Comment by YVeselovskyi** [comment]
@Zyie, thanks a lot, I chose the second option :)

**Comment by Zyie** [comment]
Thanks for being so patient with this, i'll try and fix this issue as soon as i can!

**Comment by alexandermake** [comment]
same problem,with cacheBust: true - font family has hashed name, for example name + hash: Arial cfq4.
